version: 2
target-branch: develop
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: '11:00'
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: '11:00'
  open-pull-requests-limit: 10
