on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  install_static_narrative_and_test:
    strategy:
      fail-fast: false
      matrix:
        python: ['3.10', '3.11', '3.12']

    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@master

    - name: Set up python ${{ matrix.python }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}

    - name: install prerequisites
      shell: bash -l {0}
      run: |
        cat requirements.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -n 1 pip install
        cat requirements-test.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -n 1 pip install

    - name: Run tests
      shell: bash -l {0}
      env:
        KBASE_CI_TOKEN: ${{ secrets.KBASE_CI_TOKEN }}
      run: |
        sh test/run_tests.sh

    - name: Send to Codecov
      id: send_to_codecov
      uses: codecov/codecov-action@main
      continue-on-error: true
      with:
        files: ./python-coverage/coverage.xml
        fail_ci_if_error: true
